apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-project
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: sofienech/gestion_backend:10
          name: backend
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://service-database:80/test

