apiVersion: v1
kind: Service
metadata:
  namespace: devops-project
  name: service-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8081
  type: LoadBalancer
  