apiVersion: v1
kind: Service
metadata:
  namespace: devops-project
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  