apiVersion: v1
kind: Service
metadata:
  namespace: devops-project
  name: service-database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5432
  type: NodePort
  